<?php

// Admins' CP Language Pack for Discuz! Version 1.0.0
// Discuz Việt! – Develope, translate and support by DiscuzViet Group

$msglang = array
(
	'undefined_action' => ' bạn có hành động kỳ quặc ',
	'noaccess' => 'Bạn chưa đủ quyền truy cập khu vực quản lý',
	'noaccess_isfounder' => 'Bạn chưa đủ quyền truy cập khu vực này, cài đặt này chỉ người sáng lập diễn đàn được dùng',
	'noaccess_ip' => 'địa chỉ IP của bạn không được phép vào phạm vi này',
	'action_noaccess' => 'Xin lỗi, Admin giới hạn quyền của bạn để sử dụng tính năng này',
	'action_noaccess_config' => 'Admin đã đóng chức năng này, nếu bạn muốn kích hoạt chức năng hãy sửa config.inc.php',
	'action_access_noexists' => 'Diễn đàn thiết lập thiếu an toàn, xem lại file config.inc.php cẩn thận để sửa đổi cấu hình của bạn. Nếu không, bạn không thể sử dụng tính năng này.',
	'import_data_invalid' => 'Dữ liệu không có giá trị',
	'import_data_typeinvalid' => 'Kiểu dữ liệu lỗi, xin vui lòng trở lại',

	'settings_gzip_invalid' => 'Bản PHP hiện tại không hỗ trợ nén Gzip.',
	'settings_maxonlines_invalid' => 'Phải nhập số lượng người online lớn nhất và không quá 65535，quay lại để thực hiện',
	'settings_creditsformula_invalid' => 'Công thức tính điểm có chứa một biến không hợp lệ, hãy quay lại để thực hiện',
	'settings_ipaccess_invalid' => 'Hành động không hợp lệ! IP của bạn không có trong Danh sách IP được phép, hãy quay lại',
	'settings_adminipaccess_invalid' => 'Hành động không hợp lệ! IP của bạn không có trong Danh sách IP được phép, hãy quay lại',
	'settings_credits_title_invalid' => 'Bạn phải nhập tên cho các loại điểm đã chọn',
	'settings_creditstrans_invalid' => 'Điểm giao dịch được kích hoạt phải là số nguyên, xin vui lòng quay lại sửa đổi',
	'settings_update_succeed' => 'Cấu hình tổng thể đã cập nhật thành công',
	'settings_seccodewidthheight_invalid' => 'Mã hình ảnh xác minh có chiều rộng hoặc chiều cao vượt ngoài phạm vi giới hạn, xin vui lòng quay lại sửa đổi',
	'settings_extcredits_must_available' => 'Bạn cần ít nhất 1 loại điểm để mở rộng, hãy trở về sửa đổi',

	'uc_database_connect_error' => 'Kết nối uCenter đến người sử dụng không thành công, hãy quay lại kiểm tra các thiết lập',
	'uc_database_select_db_error' => 'Cơ sở dữ liệu uCenter có thể không tồn tại, xin hãy trở lại để kiểm tra các thiết lập',
	'uc_config_write_error' => 'Việc lưu tập tin cấu hình không thành công, quay trở lại để kiểm tra các thiết lập',

	'forums_add_category_succeed' => 'Thể loại <b>$newcat</b> đã thêm thành công',
	'forums_add_forum_succeed' => 'Diễn đàn <b>$newforum</b> đã thêm thành công',
	'forums_update_succeed' => 'Thiết lập diễn đàn đã được cập nhật',
	'forums_copy_source_invalid' => 'Bạn đã không chọn diễn đàn nguồn để sao chép, quay trở lại để kiểm tra',
	'forums_copy_target_invalid' => 'Bạn đã không chọn diễn đàn đích để sao chép, quay trở lại để kiểm tra',
	'forums_copy_options_invalid' => 'Chức năng để sao chép không có giá trị, xin vui lòng quay lại sửa đổi',
	'forums_copy_succeed' => 'Sao chép thiết lập của diễn đàn thành công',
	'forums_moderators_update_succeed' => 'Moderator Settings đã được cập nhật',
	'forums_merge_source_sub_notnull' => 'Vẫn còn diễn đàn con, xin vui lòng quay lại để sửa đổi',
	'forums_merge_succeed' => 'Đã trộn diễn đàn thành công',
	'forums_edit_name_invalid' => 'Bạn nhập tên thể loại/board không có giá trị, xin vui lòng quay lại để sửa đổi',
	'forums_edit_sub_notnull' => 'Vẫn còn diễn đàn con, xin vui lòng quay lại để sửa đổi',
	'forums_edit_succeed' => 'Diễn đàn đã được cập nhật',
	'forums_delete_sub_notnull' => 'Vẫn còn diễn đàn con, xin vui lòng quay lại để sửa đổi',
	'forums_delete_confirm' => 'Hành động này không thể khôi phục, bạn có chắc muốn xoá bỏ những bài viết, và đính kèm?<br />Lưu ý: Hủy diễn đàn sẽ không cập nhật lại số người sử dụng và các điểm viết bài',
	'forums_delete_succeed' => 'Diễn đàn đã bị xóa',
	'forums_nonexistence' => 'Diễn đàn được chỉ định không tồn tại, xin hãy trở lại sửa đổi',
	'forums_threadtypes_duplicate' => 'Phân loại chủ đề này đã có, hãy trở lại sửa đổi',
	'forums_threadtypes_succeed' => 'Cập nhật thành công Phân loại chủ đề',
	'forums_threadsorts_duplicate' => 'Không cho phép thể hiện một loạt các thông tin phân loại, xin vui lòng quay lại để sửa đổi',
	'forums_rules_nopermission' => 'Bạn chưa đủ quyền để sửa Nội quy',
	'forums_rules_succeed' => 'Nội quy đã được cập nhật',
	'forums_noparent' => 'Bạn chưa chọn diễn đàn cấp cao hơn, quay trở lại để sửa đổi',
	'forums_name_toolong' => 'Diễn đàn có tên dài hơn 50 ký tự, quay trở lại để sửa đổi',
	'forums_formulaperm_error' => 'Thiết lập quyền hạn gặp sự cố, xin vui lòng quay lại để sửa đổi',
	'forums_delete_alarm' => 'Thao tác này không thể phục hồi, toàn bộ dữ liệu diễn đàn này sẽ bị xóa...',
	'forums_edit_nonexistence' => 'Xin hãy chọn diễn đàn mà bạn muốn sửa:',
	'forums_edit_threadsort_nonexistence' => 'Chưa chọn phân loại mặc định, hãy trở về sửa đổi',

	'announce_nonexistence' => 'Thông báo chỉ định không tồn tại hoặc không có quyền sửa đổi, xin vui lòng trở lại',
	'announce_time_invalid' => 'Bạn nhập vào thời gian bắt đầu hoặc kết thúc không đúng, xin vui lòng quay lại để sửa đổi',
	'announce_invalid' => 'Bạn phải nhập tiêu đề và nội dung của thông báo này, xin vui lòng quay lại để sửa đổi',
	'announce_succeed' => 'Thông báo đã chỉnh sửa hoàn tất',
	'announce_update_succeed' => 'Đã cập nhật nội dung thông báo',

	'modcp_ann_empty' => 'Bạn phải nhập tiêu đề và nội dung của thông báo này, xin vui lòng quay lại để sửa đổi',
	'modcp_ann_urlerror' => 'URL không hợp lệ, xin vui lòng quay lại để sửa đổi',

	'admingroups_edit_succeed' => 'Các thiết lập quyền hạn cho nhóm Admin đã được sửa',
	'admingroups_edit_nonexistence' => 'Hãy lựa chọn nhóm quản lý của bạn để tiến hành các hoạt động:',

	'usergroups_update_credits_invalid' => '"UserGroup" settings không có giá trị hoặc 0 thành viên trong nhóm, xin vui lòng quay lại sửa đổi',
	'usergroups_update_credits_duplicate' => 'Các cấu hình cho nhóm người sử dụng với hạn mức thấp đã có',
	'usergroups_update_succeed' => 'Đã thêm một nhóm người dùng mới. <br />Xin đừng quên cấp quyền hạn thích hợp cho nhóm',
	'usergroups_edit_public_invalid' => 'Nhóm người dùng công cộng không thể liên kết với các nhóm quản lý, hoặc sẽ có một nguy cơ về bảo mật, quay trở lại để sửa đổi',
	'usergroups_edit_creditstrans_disabled' => 'Bạn cần phải bật hệ thống điểm giao dịch, thiết lập lệ phí liên quan đến nhóm người sử dụng công cộng',
	'usergroups_edit_rate_invalid' => 'Cấu hình hệ thống giới hạn điểm, thời gian cho UserGroup này không đúng',
	'usergroups_edit_succeed' => 'User-group permissions settings đã cập nhật',
	'usergroups_type_nonexistence' => 'Nhập sai kiểu Usergroup hoặc nó không tồn tại',
	'usergroups_edit_nonexistence' => 'Hãy chọn nhóm người dùng bạn muốn thao tác:',
	'usergroups_edit_fail' => 'Bạn không được phép chỉnh sửa một người dùng có quyền hạn của nhóm Admin',

	'ranks_succeed' => 'Cấp bậc viết bài đã được cập nhật',

	'members_add_toolong' => 'Tên người dùng của bạn dài hơn 15 ký tự, trở về nhập vào một tên ngắn hơn',
	'members_add_tooshort' => 'Tên mà bạn nhập ít hơn 3 ký tự, hãy trở về nhập lại',
	'members_add_illegal' => 'Tên người dùng chứa các ký tự nhạy cảm hoặc bị chặn bởi hệ thống của chúng tôi, xin vui lòng quay lại',
	'members_username_protect' => 'Tên người dùng có chứa các ký tự được bảo vệ từ hệ thống, xin vui lòng trở lại',
	'members_add_invalid' => 'Bạn không phải hoàn tất các thông tin người sử dụng, xin vui lòng quay lại để sửa đổi',
	'members_add_username_duplicate' => 'Tên người sử dụng đã tồn tại, quay trở lại để sửa đổi',
	'members_add_username_activation' => 'Tên người dùng đã tồn tại, nhưng chưa được kích hoạt, trở về sửa đổi',
	'members_email_duplicate' => 'Địa chỉ email đã được đăng ký, xin hãy điền cái mới',
	'members_email_illegal' => 'Email này không có giá trị hoặc bị cấm',
	'members_email_domain_illegal' => 'Email có chứa tên miền bị cấm hoặc không giá trị',
	'members_add_succeed' => 'Đã thêm $newusername(UID $uid) vào hệ thống',
	'members_search_invalid' => 'Bạn không cung cấp điều kiện tìm kiếm, xin vui lòng trở lại',
	'members_search_noresults' => 'Không tìm thấy thành viên đủ điều kiện này',
	'members_delete_confirm' => 'Hành động này không thể phục hồi, bạn có chắc muốn xoá $membernum ?',
	'members_delete_succeed' => 'Người sử dụng đủ điều kiện $numdeleted này đã bị xóa',
	'members_edit_nonexistence' => 'Người sử dụng được chỉ định không tồn tại',
	'members_edit_illegal' => 'Bạn không thể sửa người dùng đặc biệt, quay trở lại',
	'members_edit_reason_invalid' => 'Bạn không nhập lý do thực hiện thay đổi này, xin vui lòng trở lại sửa đổi.',
	'members_edit_duplicate' => 'Tên người sử dụng mới đổi bị trùng người khác, hãy trở lại sửa đổi',
	'members_edit_succeed' => 'Thông tin người sử dụng cập nhật thành công',
	'members_edit_groups_toomany' => 'bạn đã thiết lập quá nhiều nhóm người sử dụng mở rộng, vượt quá khả năng lưu trữ mà hệ thống cho phép, xin vui lòng trở lại thay đổi',
	'members_edit_groups_illegal' => 'Nhóm đã hết hạn sử dụng và người sử dụng hiện tại đang thuộc về nhóm này, xin vui lòng trở lại sửa đổi',
	'members_edit_groups_succeed' => 'Chỉnh sửa thuộc tính nhóm người sử dụng của người dùng thành công.',
	'members_edit_credits_succeed' => 'Điểm của người dùng đã sửa thành công',
	'members_edit_medals_nonexistence' => 'Không có huy chương này, đến "Hệ thống huy chương" bắt đầu cho hoạt động này.',
	'members_edit_medals_succeed' => 'Huy chương của người dùng đã được sửa',
	'members_newsletter_sm_invalid' => 'Bạn đã không nhập tiêu đề hoặc nội dung của newsletter, quay trở lại để sửa đổi.',
	'members_newsletter_notify_succeed' => 'Newsletter của Diễn đàn đã gửi thành công.',
	'members_reward_invalid' => 'Thao tác thưởng điểm này không có giá trị, quay về hệ thống điểm để thay đổi',
	'members_reward_succeed' => 'Thực hiện thành công hệ thống điểm thưởng và hình phạt cho người sử dụng',
	'members_reward_notify_succeed' => 'Hệ thống điểm thưởng và hình phạt đã được thông báo đến người sử dụng có liên quan.',
	'members_confermedal_succeed' => 'Thực hiện thành công việc cấp phát huy chương',
	'members_confermedal_notify_succeed' => 'Trao tặng huy chương thực hiện thành công, và đã thông báo đến người sử dụng có liên quan.',
	'members_merge_invalid' => 'Bạn đã không nhập tên thành viên bạn muốn kết hợp, hoặc những người sử dụng chỉ định không tồn tại, quay trở lại để sửa đổi.',
	'members_merge_confirm' => 'Hành động này không thể phục hồi, bạn xác định rằng $sourcemember với tất cả thông tin sẽ trộn vào $targetmember bạn có muốn xóa $sourcemember ?',
	'members_merge_succeed' => 'Thành viên $sourcemember đã được tích hợp vào người dùng này: $targetmember ',
	'members_sameness' => 'Xin lỗi, tên người dùng ban đầu không thể giống như tên người dùng mục tiêu, hãy quay lại để sửa đổi.',
	'members_add_admin_none' => 'Xin lỗi, vì lý do bảo mật, không cho phép trực tiếp thêm một quản trị viên, xin vui lòng quay lại để sửa đổi.',
	'members_add_ban_all_none' => 'Tha cho tôi, tôi không cho phép bạn thêm người bị chặn IP, khách thăm, và các nhóm người sử dụng bị cấm',
	'members_no_find_deluser' => 'Không cần phải loại bỏ người dùng, quay trở lại để sửa điều kiện tìm kiếm hoặc chọn người dùng mà bạn muốn xóa',
	'members_dont_contain_admin_merge' => 'Nội dung bao gồm cả quản trị viên. Bạn không thể hợp nhất. Xin vui lòng xóa các quyền quản trị trước khi tiếp tục',
	'members_super_edit_admin_allow' => 'Người sáng lập ra diễn đàn mới có thể sửa đổi thông tin quản trị viên',
	'members_access_succeed' => 'User Permission đã được sửa',
	'members_ipban_nopermission' => 'Chỉ quản trị viên có thể sử dụng "*" là ký tự đại diện, xin vui lòng trở lại.',
	'members_ipban_illegal' => 'IP của bạn có trong danh sách bị cấm, xin vui lòng quay lại để sửa đổi',
	'members_ipban_invalid' => 'IP đã tồn tại trong danh sách, xin vui lòng trở lại',
	'members_ipban_succeed' => 'Cập nhật danh sách IP bị cấm thành công.',
	'members_nonexistence' => 'Nhập tên người dùng của bạn để thực hiện',

	'moderate_members_succeed' => 'Xét duyệt thành viên thành công, tổng cộng $numvalidated người dùng được thông qua, $numinvalidated đã bị từ chối, $numdeleted người dùng bị loại bỏ.',
	'moderate_threads_succeed' => 'Duyệt chủ đề thành công, có tổng cộng $validates chủ đề được thông qua, $ignores bị bỏ qua, $recycles trong thùng rác, $deletes bị xóa',
	'moderate_replies_succeed' => 'Duyệt bài viết thành công, có tổng cộng $validates bài được thông qua, $ignores bị bỏ qua, $deletes bài bị xóa',
	'moderate_posts_no_access_all' => 'Bạn không có quyền xét duyệt bất kỳ bài đăng nào, xin vui lòng trở lại.',
	'moderate_posts_no_access_this' => 'Bạn không có quyền xét duyệt phần này, xin vui lòng trở lại.',
	'threads_move_invalid' => 'Bạn chưa chọn Diễn đàn mục tiêu / Chủ đề không tồn tại, xin hãy trở lại.',
	'threads_forumstick_del_succeed' => 'Danh sách Sticky Topic cập nhật thành công',
	'threads_forumstick_edit_succeed' => 'Diễn đàn mục tiêu thay đổi thành công',
	'threads_forumstick_add_succeed' => 'Chủ đề được stick thành công',
	'threads_forumstick_targets_empty' => 'Hãy chọn một hoặc nhiều  Diễn đàn mục tiêu',
	'threads_forumstick_url_invalid' => 'URL bạn nhập vào không hợp lệ',

	'recyclebin_succeed' => 'Recycle Bin cập nhật thành công, tổng số chủ đề $threadsdel bị xóa, $threadsundel được phục hồi.',
	'recyclebin_none_selected' => 'Chưa chọn bài viết để thao tác',

	'google_succeed' => 'Google Search Settings successfully updated',

	'qihoo_adminemail_invalid' => 'Webmaster Email you fill out not correct, please return the modified',
	'qihoo_succeed' => 'Search settings successfully updated',
	'qihoo_topics_succeed' => 'Topic special settings successfully updated',

	'alipay_ratio_invalid' => 'The cash/credit ratio less than 0, this is invalid',
	'alipay_account_invalid' => 'Account invalid',
	'alipay_securitycode_invalid' => 'Security code invalid',
	'alipay_succeed' => 'Set Alipay function successfully',
	'tenpay_bargainor_invalid' => 'Please enter a 10-digit number for the fiscal pay-pass merchant',
	'tenpay_key_invalid' => 'Keys only be used 32 letters or numbers, please return to modify',
	'tenpay_succeed' => 'Finance successfully set up to pay',
	'ec_credit_succeed' => 'Set credit evaluation system successfully',

	'orders_disabled' => 'Bạn chưa mở hệ thống giao dịch, không thể quản lý phiếu đặt hàng.',
	'orders_validate_succeed' => 'Phiếu Đặt hàng xử lý thành công',

	'magics_config_succeed' => 'Cấu hình Thẻ VIP đã cập nhật',
	'magics_data_succeed' => 'Thông tin Thẻ VIP đã cập nhật',
	'magics_parameter_invalid' => 'Tham số điền không đầy đủ, xin vui lòng quay lại để sửa đổi.',
	'magics_identifier_invalid' => 'Trùng định danh thẻ VIP',
	'magics_filename_illegal' => 'Tên file Thẻ mà bạn nhập vào có chứa các ký tự bị chặn, quay lại để sửa đổi.',
	'magics_filename_invalid' => 'File ($magicfile) không tồn tại hoặc lỗi',
	'magics_present_invalid' => 'Quà tặng phải có ít nhất một loại Thẻ khác, trở về sửa đổi',

	'medals_succeed' => 'Huy chương đã sửa thành công',
	'medals_validate_succeed' => 'Đã kiểm tra, xét duyệt huy chương',
	'medals_invalidate_succeed' => 'Ứng dụng của Medal đã bị loại bỏ',
	'medals_add_succeed' => 'Đã thêm huy chương',
	'medals_please_input' => 'Chọn các hoạt động cần huy chương',

	'tasks_succeed' => 'Đã thêm nhiệm vụ',
	'tasks_settings_invalid' => 'Một vài cấu hình cho nhiệm vụ chưa được kích hoạt',
	'tasks_noscript_or_nocfg' => 'File cấu hình nhiệm vụ bị lỗi hoặc không có script này',
	'tasks_basic_invalid' => 'Nhiệm vụ chưa được cấu hình hoàn tất',
	'tasks_time_invalid' => 'Cấu hình thời gian online, offline không hợp lý',
	'tasks_reward_invalid' => 'Phần thưởng của nhiệm vụ cấu hình không hợp lý',
	'tasks_del_confirm' => 'Bạn chắc chắn muốn xóa nhiệm vụ này ?',
	'tasks_del' => 'Đã xóa nhiệm vụ',
	'tasks_code_invalid' => 'Script nhiệm vụ không đáp ứng các thông số kỹ thuật, không thể cài đặt, xin vui lòng liên hệ với tác giả.',
	'tasks_install_duplicate' => 'Nhiệm vụ này đã có rồi, xin quay lại',
	'tasks_installed' => 'Nhiệm vụ đã cài đặt xong',
	'tasks_uninstall_confirm' => 'Hành động này sẽ gỡ bỏ nhiệm vụ hiện tại và loại bỏ tất cả thông tin liên quan, hãy chắc chắn!',
	'tasks_noscript' => 'File script của nhiệm vụ không tồn tại',
	'tasks_uninstalled' => 'Đã gỡ bỏ nhiệm vụ',
	'tasks_newest' => 'Vui lòng tải lên một phiên bản mới hơn của nhiệm vụ, và sau đó làm mới trang.',
	'tasks_updated' => 'Nhiệm vụ đã được cập nhật',
	'tasks_newbie_setting_invalid_tid' => 'Bạn phải thiết lập một chủ đề cụ thể, xin vui lòng quay lại để sửa đổi.',
	'tasks_newbie_setting_invalid_fid' => 'Bạn phải thiết lập một forum được chỉ định, quay trở lại để sửa đổi.',
	'tasks_newbie_setting_invalid_uid' => 'Bạn phải thiết lập một thành viên cụ thể, xin vui lòng quay lại để sửa đổi.',

	'counter_forum_succeed' => 'Đã xây dựng lại số bài viết của diễn đàn',
	'counter_digest_succeed' => 'Đã xây dựng lại số bài hay',
	'counter_member_succeed' => 'Đã xây dựng lại số thành viên viết bài',
	'counter_thread_succeed' => 'Đã xây dựng lại số chủ đề được đăng',
	'counter_moved_thread_succeed' => 'Đã xây dựng lại số chủ đề bị di chuyển',
	'counter_moved_favorites_logs_succeed' => 'Đã xóa favorites log data',
	'counter_special_arrange_succeed' => 'Đã sắp xếp phân loại thông tin dữ liệu',

	'database_export_custom_invalid' => 'Bạn cần chọn ít nhất một table dữ liệu để sao lưu, xin vui lòng quay lại để sửa đổi.',
	'database_export_file_invalid' => 'Tập tin không thể lưu vào máy chủ, kiểm tra các thuộc tính thư mục lưu trữ.',
	'database_export_multivol_redirect' => 'Multi-volume backup: các file #$volume được tạo thành công, chương trình sẽ tự động tiếp tục.',
	'database_export_succeed' => 'Đã sao lưu với tên file <a href=\"$filename\">$filename</a> ',
	'database_export_filename_invalid' => 'Bạn đã không nhập tên tập tin sao lưu hoặc tập tin sử dụng phần mở rộng nhạy cảm, xin vui lòng quay lại để sửa đổi.',
	'database_export_multivol_succeed' => 'Xin chúc mừng, các file $volume đã tạo thành công. Công việc kết thúc\n<br />$filelist',
	'database_export_zip_succeed' => 'File nén đã lưu với tên <a href=\"$filename\">$filename</a>',
	'database_export_dest_invalid' => 'Thư mục ./forumdata/ này không tồn tại hoặc không thể truy cập',
	'database_import_multivol_succeed' => 'Multi-volume data đã import vào database',
	'database_import_file_illegal' => 'Tập tin dữ liệu không tồn tại: có thể do máy chủ không cho phép tải lên hoặc kích thước file vượt quá giới hạn.',
	'database_import_format_illegal' => 'Đây là kiểu định dạng của Discuz Việt!',
	'database_import_multivol_prompt' => 'Multi-volume data đã import vào database, bạn có muốn tự động import các file backup khác ?',
	'database_import_multivol_redirect' => 'Đã import #$dumpinfo[volume] thành công, chương trình sẽ tự động tiếp tục.',
	'database_import_confirm' => 'Dữ liệu import và phiên bản Discuz hiện tại không khớp! Có khả năng bị lỗi, bạn có muốn tiếp tục?',
	'database_import_unzip' => '$info<br /> file data sao lưu đã được giải nén, có muốn tự động import bản sao lưu này ? Sau khi import các file trích xuất sẽ bị xóa.',
	'database_import_multivol_unzip' => '$info<br /> Extract the backup file is completed, do you want automatically extract other multi-volumes file?',
	'database_import_multivol_unzip_redirect' => 'File sao lưu #$multivol đã giải nén, chương trình tự tiếp tục công việc',
	'database_import_multivol_confirm' => 'Tất cả các file sao lưu dạng multi-volume đã giải nén, bạn có muốn import tự động bản sao lưu này ? Khi hoàn tất các file trích xuất sẽ bị xóa',
	'database_import_succeed' => 'Dữ liệu import thành công vào cơ sở dữ liệu của Diễn đàn.',
	'database_shell_fail' => 'Server không hỗ trợ Shell, bạn không thể dùng MySQL Dump để xuất/nhập database',
	'database_file_delete_succeed' => 'File sao lưu đã bị xóa',
	'database_file_delete_invalid' => 'Chưa chọn file database để xóa, quay lại nào',
	'database_run_query_invalid' => 'Có lỗi MySQL sau: {$sqlerror}',
	'database_run_query_succeed' => 'Cấu trúc dữ liệu cập nhật thành công, có {$affected_rows} rows bị ảnh hưởng',

	'adv_config_succeed' => 'Cấu hình hệ thống Quảng cáo đã được cập nhật',
	'adv_title_invalid' => 'Bạn chưa điền tiêu đề quảng cáo, xin vui lòng quay lại sửa đổi',
	'adv_endtime_invalid' => 'Bạn đã nhập thời gian kết thúc sớm hơn thời gian hiện hành',
	'adv_parameter_invalid' => 'Cần phải hoàn tất các thông số tương ứng với yêu cầu',
	'adv_update_succeed' => 'Đã cập nhật danh sách quảng cáo',
	'adv_succeed' => 'Việc thêm, cập nhật quảng cáo hoàn tất',
	'adv_title_more' => 'Tiêu đề của quảng cáo nhiều hơn 50 ký tự, hãy trở về sửa đổi',

	'crons_filename_illegal' => 'Tên công việc theo kịch bản có chứa các ký tự bất hợp pháp, xin vui lòng quay lại sửa đổi',
	'crons_filename_invalid' => 'Cron-job file ($cronfile) không tồn tại hoặc có lỗi cú pháp, xin vui lòng quay lại sửa đổi',
	'crons_time_invalid' => 'Bạn chưa chỉ định thời gian thực hiện công việc',
	'crons_succeed' => 'Đã cập nhật công việc theo kịch bản',
	'crons_run_invalid' => 'File kịch bản: ($cronfile) không tồn tại hoặc có lỗi cú pháp',
	'crons_run_succeed' => 'Cron-job thực thi hoàn tất',

	'onlinelist_succeed' => 'Đã cập nhật Online list',
	'forumlinks_succeed' => 'Đã cập nhật link Partner',
	'censor_succeed' => 'Đã cập nhật bộ lọc Words Filter ',
	'censor_batch_add_succeed' => 'Có tổng số từ mới: <b>($newcount)</b>, <b>($updatecount)</b> được cập nhật, <b>($ignorecount)</b> bỏ qua',
	'censor_keywords_tooshort' => 'Từ khóa chiều dài quá ngắn, ít nhất có 3 ký tự',
	'censor_keywords_existence' => 'Hiện đã có từ khóa này, không thêm điều kiện trùng lặp, xin vui lòng quay lại đổi',
	'smilies_type_nonexistence' => 'Thể loại smile này không tồn tại',
	'smilies_delete_invalid' => 'Bạn không thể trực tiếp xóa smile category',
	'smilies_edit_succeed' => 'Smilies đã được sửa',
	'smilies_import_succeed_renamed' => 'Thể loại smilies này đã được import và đổi tên mới',
	'smilies_import_succeed' => 'Thể loại smilies này đã được import',
	'smilies_directory_invalid' => 'Thư mục smilies $smurl không tồn tại，bạn có thể tạo thư mục $smurl qua FTP và tải lên smilies tương ứng.',
	'smilies_update_succeed' => 'Updated, found $num smile in $smurl directory, all has been added to category $smtype[name]',
	'smilies_update_error' => 'Directory $smurl has no new smile, please check.<br />You can upload smile via FTP to $smurl, and refresh this page.',
	'thread_icon_succeed' => 'Topic icon update successful',
	'thread_stamp_succeed' => 'Tem chủ đề đã được cập nhật',
	'attachtypes_duplicate' => 'Đuôi mở rộng này đã có, vui lòng trở lại sửa đổi',
	'attachtypes_succeed' => 'Kiểu tập tin đính kèm cập nhật thành công',

	'styles_export_invalid' => 'Template chỉ định không tồn tại, không thể xuất',
	'styles_delete_invalid' => 'Bạn không thể trực tiếp xóa các template mặc định của hệ thống, xin vui lòng quay lại chọn một template khác làm mặc định và sau đó xoá nó',
	'styles_delete_invalid_default' => 'Nếu bạn không thích template này, bạn có thể vô hiệu hóa nó nhưng đừng xóa ID.',
	'styles_edit_succeed' => 'Đã cập nhật template',
	'styles_import_version_invalid' => 'Template này áp dụng cho Discuz Việt! ver. $stylearray[version]; với phiên bản hiện tại ($version) là không thể sử dụng',
	'styles_import_version_invalid_confirm' => 'Template này áp dụng cho Discuz Việt! ver. $stylearray[version] với phiên bản hiện tại ($version) là không thể sử dụng, bạn có muốn tiếp tục cài ?',
	'styles_import_directory_invalid' => 'Hãy CHMOD thư mục $basedir là 777<br />Hoặc vào FTP để tạo thư mục $stylearray[directory] CHMOD 777',
	'styles_import_succeed_renamed' => 'Template nhập vào hoàn tất, nó bị trùng lặp và đã được tự động đổi tên',
	'styles_import_succeed' => 'Import Template thành công',
	'styles_install_succeed' => 'Cài đặt Template hoàn tất',
	'styles_edit_variable_duplicate' => 'Tên biến đã tồn tại, hãy trở về sửa đổi',
	'styles_edit_variable_illegal' => 'Tên các biến thay thế mới không được chấp nhận, trở về sửa đổi',
	'styles_copy_succeed' => 'Sao chép Template thành công',
	'styles_nonexistence' => 'Hãy lựa chọn Template bạn muốn thực hiện:',

	'tpl_directory_invalid' => 'Thư mục $directory không tồn tại trong ./templates ; hoặc thiếu dấu \"/\" ',
	'tpl_new_directory_invalid' => 'Bạn chưa điền vào thư mục template',
	'tpl_default_directory_invalid' => 'Bạn không thể sửa các thiết lập của template mặc định',
	'tpl_delete_invalid' => 'Bạn không thể xóa template mặc định',
	'tpl_update_succeed' => 'Template đã được cập nhật',
	'tpl_reset_confirm' => 'Bạn muốn khôi phục template $template[directory]/$fn làm template mặc định ?',
	'tpl_reset_succeed' => 'Template đã được reset và được chuyển vào danh sách',
	'tpl_edit_nonexistence' => 'Assigns the template wrap does not exist, please return',
	'tpl_edit_invalid' => 'Các tập tin $template[directory]/$fn không ghi được<br />Hãy CHMOD cho chúng là 777',
	'tpl_edit_succeed' => 'Sửa đổi thành công',
	'tpl_add_invalid' => 'Assigns the template does not exist or was deleted, please return',
	'tpl_add_duplicate' => 'New template already exists, go back to choose a different name',
	'tpl_add_file_invalid' => 'Không thể lưu file $template[directory]/$name.htm ;<br />Hãy CHMOD cho nó là 777',
	'tpl_add_succeed' => 'Template successfully added, now will go into template editing page',
	'tpl_delete_confirm' => 'Thao tác này sẽ không thể phục hồi, bạn có muốn xóa template $fn ?',
	'tpl_delete_succeed' => 'Template đã bị xóa',
	'tpl_delete_fail' => 'The program has not remove the template file, use the FTP login and try again.',
	'tpl_desctpl_exists' => 'Đã có các file $desctemplate[directory]/$fn ; bạn có muốn ghi đè lên chúng ?',
	'tpl_tplcopy_succeed' => 'Template $fn đã được copy đến $desctemplate[directory] ',
	'tpl_tplcopy_invalid' => 'Thư mục $desctemplate[directory]/$fn không thể ghi.<br />Muốn tiếp tục hãy CHMOD 777',

	'fields_edit_succeed' => 'Hệ thống Profile đã được cập nhật',
	'fields_edit_invalid' => 'The project name cannot null, return to the modified.',

	'dzcode_edit_succeed' => 'Discuz! Code updated successfully',
	'dzcode_edit_tag_invalid' => 'Code TAG is empty or contains illegal characters, please return the modified',
	'dzcode_edit_range_invalid' => 'Tham số hoặc phạm vi (range) không hợp lệ',

	'plugins_settings_module_nonexistence' => 'Plug-in ($modfile) does not exist or there is a syntax error, check to see if it was complete upload plug-ins.',
	'plugins_settings_succeed' => 'Plug-in parameter settings updated',
	'plugins_edit_name_invalid' => 'Tên plugin không hợp lệ',
	'plugins_edit_directory_invalid' => 'Thư mục plugin không có giá trị hoặc thiếu \"/\" ',
	'plugins_edit_identifier_invalid' => 'You enter a identifier has been illegal or duplication with existing plug-in',
	'plugins_edit_modules_duplicated' => 'Bạn nhập tên mô-đun trùng với tên hiện có trên hệ thống',
	'plugins_edit_modules_name_invalid' => 'Tên module chương trình không hợp lệ, xin vui lòng quay lại để sửa đổi.',
	'plugins_edit_modules_url_invalid' => 'Địa chỉ URL không hợp lệ',
	'plugins_edit_modules_menu_invalid' => 'Bạn cần nhập tên module menu, xin vui lòng quay lại để sửa đổi.',
	'plugins_edit_hooks_title_invalid' => 'Tên hook mà bạn đã nhập không hợp lệ hoặc đã có',
	'plugins_edit_language_invalid' => 'Language pack file: ($langfile) của plugin không hợp lệ',
	'plugins_edit_hooks_succeed' => 'Plug-ins hook successfully updated',
	'plugins_edit_var_invalid' => 'The configuration variable name you entered is not illegal or duplication',
	'plugins_edit_var_title_invalid' => 'You did not enter the configuration variable name',
	'plugins_edit_vars_succeed' => 'Plug-in variables configuration successfully',
	'plugins_edit_succeed' => 'Plug-in configuration successfully',
	'plugins_add_succeed' => 'Plug-ins have been successfully added, continue with the more settings.',
	'plugins_import_version_invalid' => 'Plug-in $pluginarray[version] không phù hợp với bản ($version) hiện tại',
	'plugins_import_version_invalid_confirm' => 'Plug-in $pluginarray[version] không phù hợp với bản ($version) hiện tại, bạn muốn cài tiếp ?<br />Nếu trong plug-in này giải thích rằng phần lắp đặt không chứa các tập tin làm thay đổi sourcecode có màu xanh lá, bạn có thể yên tâm cài đặt',
	'plugins_import_identifier_duplicated' => '($plugin[name]) đã có',
	'plugins_import_succeed' => 'Plug-in data imported successfully! <br />In order to properly use this plug-in, you may also need to upload or modify the corresponding file or template, please see the installation instructions in this plug-in',
	'plugins_import_hooks_title_invalid' => 'Plug-in hook name không hợp lệ',
	'plugins_import_var_invalid' => 'Plug-in variable không hợp lệ',
	'plugins_install_succeed' => 'Plug-in đã cài thành công ! <br />In order to properly use this plug-in, you may also need to modify the corresponding file or template, please see the installation instructions in this plug-in',
	'plugins_nonexistence' => 'Bạn đang thực hiện thao tác: Thiết kế plug-in. Hãy lựa chọn plug-in:',
	'plugins_delete_confirm' => 'Bạn có chắc là bạn muốn bỏ plugin ?',
	'plugins_delete_succeed' => 'Plug-in đã bị xóa.<br />In order to properly use this plug-in, you may also need to delete or modify the corresponding file or template, please see the installation instructions in this plug-in',
	'plugins_upgrade_hooks_title_invalid' => 'The plug-in hook name is not valid, cannot be upgraded',
	'plugins_upgrade_var_invalid' => 'The plug-in variable is not valid, cannot be upgraded',
	'plugins_upgrade_succeed' => 'Plug-in nâng cấp lên {$toversion} thành công！',

	'addons_provider_nonexistence' => 'Nguồn cung cấp (addon) không tồn tại, xin hãy trở lại.',
	'addons_provider_disabled' => 'Nguồn cung cấp (addon) không tồn tại hoặc đã bị disable',
	'addons_provider_apiinvalid' => 'Kết nối đến các nhà cung cấp nguồn tài nguyên (addon API) lỗi, xin vui lòng trở lại',
	'addons_provider_removesucceed' => 'Nhà cung cấp nguồn đã bị gỡ bỏ',
	'addons_provider_exists' => 'Nguồn cung cấp đã tồn tại.',
	'addons_provider_addsucceed' => 'Nguồn cung cấp đã thêm thành công',

	'trade_fee_error' => 'Thiết lập phí giao dịch không đúng, xin vui lòng quay lại để sửa đổi.',
	'reward_credits_error' => 'Điểm thưởng trên giao dịch điểm không chính xác',

	'update_cache_succeed' => 'Tất cả cache đã được cập nhật rồi đó bạn hiền',
	'csscache_update' => 'CSS cache đã được cập nhật rồi đó bạn hiền',

	'jswizard_disabled' => 'Tính năng Javascript bị disabled',
	'jswizard_overflow' => 'Vượt quá giới hạn dung lượng rồi bạn, quay trở lại để sửa thôi.',
	'jswizard_jskey_exists' => 'Tên này đã có, hãy đổi tên khác',
	'jswizard_succeed' => 'Javascript đã được cập nhật',
	'jswizard_copy_succeed' => 'Project đã được sao chép vào {$requestdata[variable]}',
	'jswizard_infoside_succeed' => 'Sidebar updated successfully',
	'jswizard_import_exist' => 'Javascript need to import already exists module name ({$existkeys})',
	'jswizard_relatedtag_succeed' => 'Tag thay thế đã cập nhật',

	'creditwizard_resetusercredit_warning' => '<font color=\"FF0000\"><b>Cảnh báo: </b></font>Thao tác này sẽ reset tất cả các thiết lập hệ thống điểm của người dùng - từ extcredits{$resetcredit} đến {$initcredits[$resetcredit]}, bạn có muốn tiếp tục ?',
	'creditwizard_resetusercredit_ok' => 'Tất cả các thiết lập hệ thống điểm đã được reset',
	'creditwizard_edit_rate_invalid' => '{$group[grouptitle]} có điểm rate giới hạn lớn nhất và nhỏ nhất, hoặc rate trong 24h cài đặt không đúng',
	'creditwizard_edit_succeed' => 'Hệ thống điểm đã được cập nhật',

	'filecheck_nofound_md5file' => 'Không tìm thấy file checksum MD5',

	'dbcheck_permissions_invalid' => 'Môi trường máy chủ của bạn không cho phép thực hiện kiểm tra cơ sở dữ liệu',
	'dbcheck_checking' => 'Đang kiểm tra Cơ sở dữ liệu, xin vui lòng chờ đợi......',
	'dbcheck_nofound_md5file' => 'Không tìm thấy file checksum database',
	'dbcheck_ok' => 'Cơ sở dữ liệu của bạn đầy đủ và chính xác',
	'dbcheck_repair_completed' => 'Việc sửa chữa cơ sở dữ liệu hoàn tất',
	'dbcheck_repair_error' => 'Cơ sở dữ liệu phục hồi thành công, nhưng vẫn còn $errorcount dữ liệu bị lỗi<br /><br />$error',

	'faq_list_update' => 'Danh sách FAQ đã cập nhật ',
	'faq_no_title' => 'Bạn phải điền vào tiêu đề, quay trở lại để sửa đổi',
	'faq_identifier_invalid' => 'Định danh của FAQ bị trùng lặp, quay trở lại để sửa đổi',
	'faq_keyword_toolong' => 'Keyword của FAQ quá dài',

	'ftp_password_short' => 'FTP có mật khẩu trên 3 ký tự, xin vui lòng quay lại để sửa đổi.',
	'cachethread_dir_noexists' => 'Thư mục $settingsnew[cachethreaddir] không tồn tại hoặc không thể ghi, truy cập vào nó qua FTP và CHMOD 777',

	'project_update_forum' => 'Thiết lập tổng thể của diễn đàn đã được cập nhật',
	'project_import_succeed' => 'Đã import Settings Project thành công',
	'project_no_title' => 'Chưa nhập tên project',
	'project_no_usergroup' => 'Bạn đã chọn nhóm người dùng không tồn tại.',
	'project_no_item' => 'Chưa điền item mà bạn muốn lưu',
	'project_sava_succeed' => 'Đã lưu Settings Project thành công',
	'project_target_item_invalid' => 'Chưa chỉ định một project nào',
	'project_no_scheme' => 'Bạn đã chọn Settings Project scheme không tồn tại',
	'project_scheme_succeed' => 'Settings Project scheme đã được cập nhật',
	'project_invalid' => 'Forum project có thông số không hợp lệ',


	'watermarkpreview_error' => 'Chức năng Watermark chưa mở, bạn không thể xem nó',
	'watermarkpreview_fontpath_error' => 'File TrueType font không tồn tại hoặc sai đường dẫn',
	'watermarkpreview_createerror' => 'Hình Watermark không thể tạo, hoặc không đáp ứng các điều kiện để tạo ra hình mờ, hãy kiểm tra các thiết lập',
	'thumbpreview_error' => 'Chức năng Thumnail [resize image] chưa mở, bạn không thể xem nó',
	'thumbpreview_createerror' => 'Không thể tạo Thumnail [resize image], hãy kiểm tra các thiết lập',

	'ecommerce_invalidcredit' => 'Giá giao dịch phải lớn hơn 0 ! Xin vui lòng quay lại để sửa đổi.',
	'ecommerce_must_larger' => 'Điểm giao dịch $rank phải lớn hơn điểm ở cấp độ trước đó',

	'tags_updated' => 'Tag của chủ đề cập nhật thành công',
	'tags_not_open' => 'Chức năng (TAG) cho chủ đề chưa kích hoạt',

	'threadtype_infotypes_succeed' => 'Chức năng phân loại chủ đề đã cập nhật',
	'threadtype_infotypes_optionvariable_invalid' => 'Tên biến của phân loại chủ đề đã có',
	'threadtype_infotypes_noexist' => 'Đối tượng phân loại không tồn tại',
	'threadtype_infotypes_option_succeed' => 'Đã cập nhật chức năng phân loại mở rộng',
	'threadtype_infotypes_option_invalid' => 'Tên biến hoặc tên chức năng của phân loại không hợp lệ',
	'threadtype_infotypes_invalid' => 'Thông tin của phân loại cần ít nhất một tùy chọn, quay trở lại để sửa đổi.',
	'threadtype_infotypes_model_succeed' => 'Model của phân loại đã được cập nhật',

	// Custom menu related
	'custommenu_edit_succeed' => 'Thao tác thường dùng đã được cập nhật',
	'custommenu_history_delete_succeed' => 'History đã được xóa',
	'custommenu_add_succeed' => '$lang[$title] đã được thêm thành công vào các thao tác thường được sử dụng, sẽ sớm quay trở lại trang trước, bạn có thể chỉnh sửa <a href=\"$BASESCRIPT?action=misc&operation=custommenu\">thao tác thường dùng tại đây</a>',
	'custommenu_history_delete_confirm' => 'Hành động này không thể khôi phục, bạn có chắc chắn muốn xóa các bản ghi hoạt động trong History ?',

	'search_result_noexists' => 'Sorry, not found the related setting<br />Please try with more keywords (use space between keywords) to have more results.',
	'search_keyword_noexists' => 'Xin nhập vào từ khóa khác để tìm kiếm !',

	'nav_add_succeed' => 'Thanh Navigator đã được cập nhật',

	'focus_update_succeed' => 'Forum recommend updated successfully',
	'focus_add_num_limit' => 'Sorry, only add maximum of 10 Forum recommend',
	'focus_add_succeed' => 'Forum recommend added successfully',
	'focus_topic_noexists' => 'Forum recommend does not exist',
	'focus_topic_exists' => 'Add Forum recommendation already exists',
	'focus_edit_succeed' => 'Forum recommend edited successfully',
	'focus_conf_succeed' => 'Forum recommended settings for success',

	'delete_position_succeed' => 'Xóa tin chỉ mục thành công',
	'select_thread_empty' => 'Chưa chọn chủ đề',
	'add_postposition_succeed' => 'Thêm 1 tin chỉ mục thành công',
	'addpostposition_continue' => 'Đang thêm 1 tin chỉ mục, đừng tắt trình duyệt',
	'delete_position_gotu_add' => 'Đã gỡ bỏ các tin chỉ mục, hệ thống đang được thay đổi để tái tạo chỉ mục, đừng tắt trình duyệt của bạn!',

);

?>