<?php

// Misc Language Pack for Discuz! Version 1.0.0
// Goi ngon ngu duoc Viet hoa boi love.itvn@gmail.com - Bien tap va chinh sua boi JaJa

$language = array
(
	'discuz_lang' => 'Ngôn ngữ',

	'anonymous' => 'Ẩn danh',

	'post_hidden' => '*** Đây là nội dung ẩn ***',
	'post_banned' => '*** Tác giả đã bị cấm hay bị xóa, nội dung tự động ẩn ***',
	'post_single_banned' => '*** Nội dung này đã bị cấm ***',
	'message_ishidden_hiddenreplies' => '*** Nội dung chỉ dành cho tác giả ***',
	'post_reply_quote' => 'Trích từ $thaquote[author] vào lúc $time',
	'post_edit' => '[i=s] Bài viết được $editor chỉnh sửa vào lúc $edittime [/i]\n\n',
	'post_edit_regexp' => '/^\[i=s\] Bài viết này được chỉnh sửa .*? vào .*?  \[\/i\]\n\n/s',
	'post_reply' => 'Trả lời',
	'post_thread' => 'Đăng bài',

	'price' => 'Giá',
	'pay_view' => 'Biên bản',
	'attachment_buy' => 'Mua',

	'post_trade_yuan' => 'Đồng',
	'post_trade_seller' => 'Người bán',
	'post_trade_name' => 'Tên SP',
	'post_trade_price' => 'Giá SP',
	'post_trade_quality' => 'Chất lượng',
	'post_trade_locus' => 'Xuất xứ',
	'post_trade_transport_type' => 'Phương thức',
	'post_trade_transport_seller' => 'Người bán chịu',
	'post_trade_transport_buyer' => 'Người mua chịu',
	'post_trade_transport_mail' => 'Email',
	'post_trade_transport_express' => 'Nhanh chóng',
	'post_trade_transport_virtual' => 'Không cần chuyển',
	'post_trade_transport_physical' => 'Nơi nhận hàng',
	'post_trade_locus' => 'Tại ',
	'post_trade_description' => 'Miêu tả sản phẩm',
	'post_trade_pm_subject' => '[Thương lượng]',
	'post_trade_pm_buynum' => 'Mua số lượng',
	'post_trade_pm_wishprice' => 'Tôi hi vọng giá là ',
	'post_trade_pm_reason' => 'Lý do mặc cả là ',
	'payment_unit' => 'Đồng',

	'attach' => 'File đính kèm',
	'attach_pay' => 'Phí đính kèm',
	'attach_credits_policy' => 'Xem cách tính điểm',
	'attach_img' => 'Hình đính kèm',
	'attach_readperm' => 'Giới hạn quyền',
	'attach_img_zoom' => 'Xem toàn hình tại cửa sổ mới\\nCTRL+con lăn của chuột để xem to nhỏ hình',
	'attach_img_thumb' => 'Xem hình chuẩn tại cửa sổ mới',
	'attach_downloads' => 'Số lần tải',

	'post_trade_transport' => 'Bưu phí',
	'post_trade_transport_mail' => 'Bằng mail',
	'post_trade_quality' => 'Chất lượng',
	'post_trade_quality_new' => 'Mới',
	'post_trade_quality_secondhand' => 'Cũ',

	'trade_unstart' => '<font color="gray">Đang chờ xử lý</font>',
	'trade_waitbuyerpay' => 'Chờ người mua trả tiền',
	'trade_waitsellerconfirm' => 'Giao dịch đã được lập, chờ người bán xác nhận',
	'trade_sysconfirmpay' => 'Đang chờ xác nhận của người mua, tạm dừng gửi hàng',
	'trade_waitsellersend' => 'Người mua đã chi trả, đợi người bán gửi hàng',
	'trade_waitbuyerconfirm' => 'Người bán đã gởi hàng, đợi xác nhận của người mua',
	'trade_syspayseller' => 'Người mua đã nhận hàng, chờ ...',
	'trade_finished' => '<font color="green">Giao dịch thành công</font>',
	'trade_closed' => '<font color="gray">Khóa Giao dịch (chưa hoàn thành)</font>',
	'trade_waitselleragree'  => 'Đợi người bán đồng ý trả lại tiền',
	'trade_sellerrefusebuyer' => 'Người bán từ chối điều kiện người mua, đợi người mua chỉnh sửa điều kiện',
	'trade_waitbuyerreturn' => 'Người bán trả lại tiền, chờ người mua nhận lại tiền',
	'trade_waitsellerconfirm' => 'Đợi người bán xác nhận hàng',
	'trade_waitalipayrefund' => 'Đôi bên thống nhất, đợi alipay trả lại tiền',
	'trade_alipaycheck' => 'Đang xử lý',
	'trade_overedrefund' => 'Kết thúc thanh toán tiền',
	'trade_refundsuccess' => '<font color="green">Thanh toán tiền thành công</font>',
	'trade_refundclosed' => '<font color="green">Thanh toán tiền đã đóng</font>',

	'trade_offline_1' => 'Đơn giao dịch có hiệu lực',
	'trade_offline_4' => 'Người mua đã trả tiền, đợi người bán gửi hàng',
	'trade_offline_5' => 'Người bán đã gửi hàng',
	'trade_offline_7' => 'Người mua đã nhận hàng, giao dịch kết thúc thành công',
	'trade_offline_8' => 'Đơn giao dịch đóng',
	'trade_offline_10' => 'Tôi muốn trả lại hàng, đợi người bán đồng ý trả lại tiền',
	'trade_offline_11' => 'Người bán từ chối trả lại tiền',
	'trade_offline_12' => 'Người bán đồng ý trả lại tiền',
	'trade_offline_13' => 'Người mua đã trả lại hàng, đợi người bán nhận lại hàng',
	'trade_offline_17' => 'Người bán đã nhận hàng, đã trả lại tiền',

	'trade_message_4' => 'Nhập vào phương thức thanh toán, số tài khoản ngân hàng và các thông tin khác',
	'trade_message_5' => 'Nhập công ty vận chuyển, vận đơn và các thông tin khác',
	'trade_message_13' => 'Nhập công ty vận chuyển, vận đơn và các thông tin khác',
	
	'reportpost_your' => 'Báo cáo',
	'reportpost_recommend' => ' trong đề xuất',
	'reportpost_delate' => ' trong báo cáo',
	'reportpost_post' => ' bài viết',
	'reportpost_yourpost' => 'bài của bạn',
	'reportpost_thread' => ' chủ đề',
	'reportpost_yourthread' => 'chủ đề của bạn',
	'reportpost_say' => 'Đã nói',

	'credit_payment' => 'Nạp điểm',
	'credit_forum_payment' => 'Nạp điểm ở diễn đàn',
	'credit_forum_royalty' => 'Phí giao dịch',

	'formulaperm_regdate' => 'Đăng ký',
	'formulaperm_regday' => 'Ngày đăng ký',
	'formulaperm_regip' => ' Địa chỉ IP đăng ký',
	'formulaperm_lastip' => 'IP lần đăng nhập cuối ',
	'formulaperm_buyercredit' => 'Buyer Feedback',
	'formulaperm_sellercredit' => 'Seller Feedback',
	'formulaperm_digestposts' => 'Số bài hay',
	'formulaperm_posts' => 'Số bài viết',
	'formulaperm_threads' => 'Số chủ đề',
	'formulaperm_oltime' => 'Thời gian trực tuyến(giờ)',
	'formulaperm_pageviews' => 'Số trang xem',
	'formulaperm_and' => 'và',
	'formulaperm_or' => 'hoặc',
	'formulaperm_extcredits' => 'Tự định nghĩa điểm',

	'login_normal_mode' => 'Bình thường',
	'login_switch_invisible_mode' => 'Đang chuyển đến: Ẩn mặt',
	'login_switch_normal_mode' => 'Đang chuyển đến: Bình thường',
	'login_invisible_mode' => 'Ẩn mặt',

	'eccredit_explain' => 'Giải thích',

	'google_site_0' => 'Google 1',
	'google_site_1' => 'Google 2',
	'google_sa' => 'Google SA',

	'modcp_logs_action_home' => 'Trang điều khiển',
	'modcp_logs_action_announcements' => 'Quản lý thông báo',
	'modcp_logs_action_members' => 'Quản lý thành viên',
	'modcp_logs_action_forumaccess' => 'Quyền hạn thành viên',
	'modcp_logs_action_forums' => 'Phần thiết lập',
	'modcp_logs_action_report' => 'Báo cáo',
	'modcp_logs_action_moderate' => 'Quản lý',
	'modcp_logs_action_login' => 'Đăng nhập',
	
	'uch_selectalbum' => 'Chọn Album',
	'uch_noalbum' => 'Không có album，',
	'click_here' => 'Nhấn vào đây',
	'uch_createalbum' => 'Tạo Album!',

	'pm_from' => 'Gửi từ',
	'pm_to' => 'Người nhận',
	'pm_date' => 'Ngày',
	
	'share_message' => 'Xin chào! $bbname, Mình thấy bài viết này có giá trị, đặc biệt gửi cho bạn.\\n\\n$thread[subject]\\n Địa chỉ là $threadurl\\n\\n hy vọng bạn thích nó.',

	'week_0' => 'C.Nhật',
	'week_1' => 'Thứ 2',
	'week_2' => 'Thứ 3',
	'week_3' => 'Thứ 4',
	'week_4' => 'Thứ 5',
	'week_5' => 'Thứ 6',
	'week_6' => 'Thứ 7',

	'notice_actor' => 'Thứ tự: $actorcount người',

	'perms_allowvisit' => 'Truy cập diễn đàn',
	'perms_readaccess' => 'Quyền đọc',
	'perms_allowviewpro' => 'Xem profile',
	'perms_allowinvisible' => 'Ẩn danh',
	'perms_allowsearch' => 'Sử dụng tìm kiếm',
	'perms_allownickname' => 'Sử dụng nickname',
	'perms_allowcstatus' => 'Tùy chọn tiêu đề',
	'perms_allowpost' => 'Tạo chủ đề',
	'perms_allowreply' => 'Gửi trả lời',
	'perms_allowpostpoll' => 'Tạo bình chọn',
	'perms_allowvote' => 'Bình chọn',
	'perms_allowpostreward' => 'Tạo bài thưởng',
	'perms_allowpostactivity' => 'Tạo bài hoạt động',
	'perms_allowpostdebate' => 'Tạo bài tranh luận',
	'perms_allowposttrade' => 'Tạo bài giao dịch',
	'perms_maxsigsize' => 'Chiều dài tối đa của chữ ký',
	'perms_allowsigbbcode' => 'Được dùng BBcode trong chữ ký',
	'perms_allowsigimgcode' => 'Được dùng thẻ [img] trong chữ ký',
	'perms_maxbiosize' => 'Ký tự tối đa ô giới thiệu bản thân',
	'perms_allowrecommend' => 'Được phép đề cử',
	'perms_allowbiobbcode' => 'Được dùng bbcode ô tự giới thiệu',
	'perms_allowbioimgcode' => 'Được dùng thẻ [img] ô tự giới thiệu',
	'perms_allowgetattach' => 'Có thể Download/Xem file đính kèm',
	'perms_allowpostattach' => 'Có thể gửi file đính kèm',
	'perms_allowsetattachperm' => 'Được dùng thẻ [img] ô tự giới thiệu',
	'perms_maxattachsize' => 'Dung lượng file đính kèm cho phép',
	'perms_maxsizeperday' => 'Số file tối đa upload trong ngày',
	'perms_allowbioimgcode' => 'Cho phép dùng thẻ [img] ô tự giới thiệu',
	'perms_attachextensions' => 'Định dạng tập tin đính kèm',
	'perms_allowstickthread' => 'Có thể đặt chú ý',
	'perms_allowdigestthread' => 'Có thể đặt bài hay',
	'perms_allowstickthread_value' => 'Chú ý',
	'perms_allowdigestthread_value' => 'Bài hay',
	'perms_allowbumpthread' => 'Có thể nâng chủ đề',
	'perms_allowhighlightthread' => 'Làm nổi bật chủ đề',
	'perms_allowrecommendthread' => 'Đề cử chủ đề',
	'perms_allowstampthread' => 'Đóng dấu chủ đề',
	'perms_allowclosethread' => 'Có thể đóng chủ đề',
	'perms_allowmovethread' => 'Có thể di chuyển chủ đề',
	'perms_allowedittypethread' => 'Có thể phân loại chủ đề',
	'perms_allowcopythread' => 'Có thể sao chép chủ đề',
	'perms_allowmergethread' => 'Có thể ghép chủ đề',
	'perms_allowsplitthread' => 'Có thể tách chủ đề',
	'perms_allowrepairthread' => 'Có thể sửa chữa chủ đề',
	'perms_allowrefund' => 'Có thể buộc trả lại điểm',
	'perms_alloweditpoll' => 'Có thể sửa bình chọn',
	'perms_allowremovereward' => 'Có thể hủy điểm bài thưởng',
	'perms_alloweditactivity' => 'Có thể quản lý sự kiện',
	'perms_allowedittrade' => 'Có thể quản lý giao dịch',
	'perms_alloweditpost' => 'Có thể sửa bài gửi',
	'perms_allowwarnpost' => 'Có thể cảnh cáo bài gửi',
	'perms_allowbanpost' => 'Cho phép khóa bài',
	'perms_allowdelpost' => 'Có thể xóa bài',
	'perms_allowviewreport' => 'Cho phép xem báo cáo',
	'perms_allowmodpost' => 'Cho phép quản lý bài gửi',
	'perms_allowmoduser' => 'Cho phép quản lý người gửi',
	'perms_allowbanuser' => 'Cho phép cấm thành viên',
	'perms_allowbanip' => 'Cho phép cấm IP',
	'perms_allowedituser' => 'Cho phép chỉnh sửa thành viên',
	'perms_allowmassprune' => 'Cho phép xóa nhiều bài viết 1 lúc',
	'perms_allowpostannounce' => 'Cho phép gửi thông báo',
	'perms_disablepostctrl' => 'Gửi bài không hạn chế',
	'perms_allowviewip' => 'Cho phép xem IP',

);

?>