<?php

// Message Pack for Discuz! WAP Version 1.0.0
// Created by Crossday

$lang = array
(

	'username' => 'Username',
	'uid' => 'UID',
	'password' => 'Password',
	'submit' => 'Submit',
	'page' => 'Page',
	'replies' => 'Replies',
	'views' => 'Views',
	'reply' => 'Reply',
	'delete' => 'Delete',
	'anonymous' => 'Anonymous',
	'forum' => 'Forum',
	'from' => 'From:',
	'type' => 'Type',
	'subject' => 'Subject',
	'message' => 'Message:',
	'home_page' => 'Home Page',
	'last_page' => 'Previous Page',
	'next_page' => 'Next Page',
	'end_page' => 'Last Page',
	'turn_page' => 'Turn Page',
	'next_thread' => 'Next Thread',
	'last_thread' => 'Prev Thread',
	'end' => 'End',
	'unread' => 'UNREAD',
	'sub_forums' => ' Sub Forums',
	'email'=> 'Email',
	'more'=> 'More',
	'search' => 'Search',
	'digest' => 'Digest',
	'reload' => 'Refresh',
	'author' => 'Author:',
	'dateline' => 'Time:',
	'return' => 'Return',
	'keywords' => 'Kewords',

	'not_loggedin' => 'You are not logged in',
	'wap_disabled' => 'WAP was disabled',
	'board_closed' => 'The board has been closed temporarily',
	'undefined_action' => 'Undefined Action',

	'home_online' => 'Online ',
	'home_members' => 'members',
	'home_newpm' => 'new PM.s',
	'home_forums' => 'Categories',
	'home_tools' => 'Tools',
	'home_newthreads' => 'View New Thread',

	'login' => 'Login',
	'login_username' => 'Username/UID',
	'login_succeed' => '{$discuz_user} has logged in successfully',
	'login_strike' => 'You have entered the wrong password for the fifth time, please wait 15 minutes before trying again',
	'login_invalid' => 'Invalid username or password, you may have 5 attempts at most. If you dont have an account, please visit {$boardurl}register.php to register and try again',
	'logout' => 'Log Out',
	'logout_succeed' => 'Logged out successfully',
	'security_question' => 'Secret Question',
	'security_answer' => 'Secret Answer',
	'security_question_0' => 'No secret question',
	'security_question_1' => 'Mamy name',
	'security_question_2' => 'Grand-father name',
	'security_question_3' => 'Fathers birthday place',
	'security_question_4' => 'Your favourite teachers name',
	'security_question_5' => 'Your computer model',
	'security_question_6' => 'Name of your favourite restaurant',
	'security_question_7' => 'The last four numbers of your driver license',

	'register' => 'Register',
	'register_username' => 'User name',
	'register_disable' => 'Register by WAP is unavailable.',
	'register_reason' => 'Registration of the reasons',
	'register_ctrl' => 'Sorry, you can register only one account within $regctrl hour',
	'register_flood_ctrl' => 'Sorry, you can register $regfloodctrl accounts in ONE day.',
	'register_manual_verify' => 'Thank you for your register. Your account will be checked by Administrator.',
	'register_succeed' => 'Thank you for your register. ',
	'activation_disable' => 'Activation through WAP is not allowed in this forum.',
	'register_activation_message' => 'The username you input, "$username" already exists in our database, please login and activate it.<br /><a href="index.php?action=login">Click here to login</a>',

	'profile_username_duplicate' => 'The name is unavailable.',
	'profile_email_duplicate' => 'The Email is unavailable for it has been used. ',
	'profile_username_illegal' => 'Some characters in your name is Forbidden.',
	'profile_username_protect' => 'Some characters in your name is Forbidden.',
	'profile_email_illegal' => 'Email is illegal, please Reset.',
	'profile_email_domain_illegal' => 'This Email service is not allowed in our forum, please input other kind of Email.',

	'fav_add_succeed' => 'Add Favorites : Successful',
	'fav_existence' => 'You have added this to your Favorites.',

	'goto_last_nonexistence' => 'This is the first topic.',
	'goto_next_nonexistence' => 'This is the last topic.',

	'forum_thread_sticky' => '[STICKY]',
	'forum_thread_digest' => '[DIGEST]',
	'forum_nopermission' => 'You dont have permission to access this forum',
	'forum_nonexistence' => 'Specified forum doesnt exist',
	'forum_list' => 'Topics list',
	'forum_sublist' => 'Subforum list',

	'my' => 'My',
	'my_uid' => 'UID:',
	'my_username' => 'Username:',
	'my_gender' => 'Gender:',
	'my_bday' => 'Birthday:',
	'my_location' => 'From:',
	'my_bio' => 'About Me:',
	'my_phone' => 'My Phone',
	'my_favorites' => 'My Favorites',
	'my_addfav' => 'Add Favorite',
	'my_nonexistence' => 'The member is unavailable.',
	'my_male' => 'Male',
	'my_female' => 'Female',
	'my_secrecy' => 'Secret',
	'my_threads' => 'My topics',
	'my_replies' => 'My replies',
	'my_fav_thread' => 'My favorite topics.',
	'my_fav_forum' => 'My favorite forums.',

	'thread_nopermission' => 'Sorry, you do not have the enough authority.',
	'thread_nonexistence' => 'Sorry, the topic is unavailable.',
	'thread_replylist' => 'Reply list',
	'thread_reply' => 'Reply:',
	'thread_quickreply' => 'Quick Reply',
	'thread_banned' => 'Banned',

	'post_reply' => 'Reply',
	'post_new' => 'New Post',
	'post_sm_isnull' => 'Error, you need input both of title and contents.',
	'post_subject_toolong' => 'Error: max-length of title is 80 characters.',
	'post_message_toolong' => 'Error: max-length of contents is {$maxpostsize}.',
	'post_message_tooshort' => 'Error: min-length of contents is {$minpostsize}',
	'post_type_isnull' => 'Error, please select the category of topic.',
	'post_flood_ctrl' => 'Two posts are limited in {$floodctrl} s',
	'post_mod_succeed' => 'Successful',
	'post_mod_forward' => 'Go to current forum.',
	'post_thread_closed' => 'The topic is unavailable,now.',
	'post_thread_closed_by_dateline' => 'The topic is unavailable,now.',
	'post_thread_closed_by_lastpost' => 'The topic is unavailable,now.',
	'post_newbie_span' => 'You can post new topic only after {$newbiespan} hours.',
	'post_hide_nopermission' => 'Sorry, you do not have the enough authority to use [hide]code.',
	'post_newthread_nopermission' => 'Sorry, you do not have the enough authority to post new topic.',
	'post_newthread_succeed' => 'Successful:<br /><a href="index.php?action=forum&amp;fid=$fid">Return</a>',
	'post_newthread_forward' => 'View topics',
	'post_newreply_nopermission' => 'Sorry, you do not have the enough authority to reply in this forum.',
	'post_newreply_succeed' => 'Successful:<br /><a href="index.php?action=forum&amp;fid=$fid">Return</a>',
	'post_newreply_forward' => 'View replies',

	'message_banned' => 'Tip: <em>Author is prohibited or remove, content automatically shielding</em>',
	'message_single_banned' => 'Tip: <em>Message has been an administrator or moderator shielding</em>',
	'admin_message_banned' => 'Tip: <em>Author banned or remove, content automatically shielding, only administrators can see</em>',
	'admin_message_single_banned' => 'Tip: <em>Message has been an administrator or moderator shield, only the administrator can be seen</em>',

	'profile_username_toolang' => 'Error : The max-length of name is 15 characters.',
	'profile_username_tooshort' => 'Error : The min-length of name is 3 characters.',
	'profile_passwd_notmatch' => 'The password confirmation you entered was incorrect ',

	'profile_passwd_illegal' => 'The password you entered was incorrect.',
	'profile_email_verify' => 'The email of confirmation was send successfully; if you can not receive the system email please check your email again.',

	'pm' => 'Private message',
	'pm_home' => 'PM Box',
	'pm_list' => 'PM List',
	'pm_unread' => 'Unviewed PMs ',
	'pm_all' => 'All PMs',
	'pm_send' => 'Send PM',
	'pm_to' => 'Receiver',
	'pm_delete_all' => 'Delete all viewed PM',
	'pm_flood_ctrl' => 'Two posts are limited in {$floodctrl}s',
	'pm_delete_confirm' => 'Confirm:Delete all viewed PM',

	'pm_sm_isnull' => 'Error: No title or contents.',
	'pm_nonexistence' => 'Unavailable PM',
	'pm_send_nonexistence' => 'Unavailable Receiver',
	'pm_send_ignore' => 'Receiver will ignore your PM.',
	'pm_send_succeed' => 'Send successfully.',
	'pm_delete_succeed' => 'Delete successfully.',

	'return_thread' => 'Return to the topic',
	'return_forum' => 'Return to the forum',

	'stats' => 'Statistics',
	'stats_threads' => 'Topics',
	'stats_posts' => 'Posts',
	'stats_members' => 'Members',

	'search' => 'Search',
	'search_result' => 'Results',
	'search_invalid' => 'Please input what you want to search.',
	'search_ctrl' => 'Sorry, you can only search one time within $searchctrl s.',
	'search_id_invalid' => 'No suitable matches were found.',
	'search_group_nopermission' => 'No suitable matches were found.',

	'goto' => 'Go to WAP',
	'wap_submit_invalid' => 'Confirmation info is invalid',
	'post_hide_reply_hidden' => 'Hidden this content',
	'register_invite' => 'The Forum invited to open the registration code, please register the way WWW',

	'message_ishidden_hiddenreplies' => 'This post is visible only to the author',

);

?>